### ISSUE TITLE
To chose the breakpoints

### ISSUE THREAD

**Issue by robsonsobral** [jackmcpickle/include-media-spread#5]
Hi, Jack.

I just found this repository and I have a question.

What if a want to chose which breakpoints are valid to spread over the property values? Can I pass a map to the mixin?

Thank you!

**Comment by jackmcpickle** [comment]
Hey @robsonsobral. Current it just loops through the include-media breakpoints and you cannot yet pass any breakpoints to it to override. 

Do you see it working as a global override? Or more like a once of thing?

Currently away on holidays back in 5days so I can solve it then. Or feel free to submit a PR with tests.

**Comment by robsonsobral** [comment]
I was thinking on a global override, but both ideas are good. It would be great to have both.

I could try to code, but I have no idea on how to write tests. I'm sorry.

I hope you have enjoyed your holidays! (and that you're reading this after them!)

Thank you, @jackmcpickle !

**Comment by jackmcpickle** [comment]
All done @robsonsobral. There was already a global override I realised. But I've renamed it to `$ims-breakpoints`. 

You can now also pass `$breakpoints: $custom-breakpoints` as a object to the mixin or the 5 variable. 

So you can use like `@include spread(padding, 1rem, 3rem, $breakpoints: $custom-breakpoints);`

**Comment by robsonsobral** [comment]
Thank you so much, @jackmcpickle ! I'm sorry I couldn't test it yet. Thank you!
